/hd create ninjaxx_top50
/hd addline ninjaxx_top50 &6&l★ TOP 50 NINJAXX ★
/hd addline ninjaxx_top50 &8&m----------------------
/hd addline ninjaxx_top50 &e#1 &f{papi: ninjaxx_top_1_name} &7- &a{papi: ninjaxx_top_1_points} pts
/hd addline ninjaxx_top50 &e#2 &f{papi: ninjaxx_top_2_name} &7- &a{papi: ninjaxx_top_2_points} pts
/hd addline ninjaxx_top50 &e#3 &f{papi: ninjaxx_top_3_name} &7- &a{papi: ninjaxx_top_3_points} pts
/hd addline ninjaxx_top50 &e#4 &f{papi: ninjaxx_top_4_name} &7- &a{papi: ninjaxx_top_4_points} pts
/hd addline ninjaxx_top50 &e#5 &f{papi: ninjaxx_top_5_name} &7- &a{papi: ninjaxx_top_5_points} pts
/hd addline ninjaxx_top50 &e#6 &f{papi: ninjaxx_top_6_name} &7- &a{papi: ninjaxx_top_6_points} pts
/hd addline ninjaxx_top50 &e#7 &f{papi: ninjaxx_top_7_name} &7- &a{papi: ninjaxx_top_7_points} pts
/hd addline ninjaxx_top50 &e#8 &f{papi: ninjaxx_top_8_name} &7- &a{papi: ninjaxx_top_8_points} pts
/hd addline ninjaxx_top50 &e#9 &f{papi: ninjaxx_top_9_name} &7- &a{papi: ninjaxx_top_9_points} pts
/hd addline ninjaxx_top50 &e#10 &f{papi: ninjaxx_top_10_name} &7- &a{papi: ninjaxx_top_10_points} pts
/hd addline ninjaxx_top50 &e#11 &f{papi: ninjaxx_top_11_name} &7- &a{papi: ninjaxx_top_11_points} pts
/hd addline ninjaxx_top50 &e#12 &f{papi: ninjaxx_top_12_name} &7- &a{papi: ninjaxx_top_12_points} pts
/hd addline ninjaxx_top50 &e#13 &f{papi: ninjaxx_top_13_name} &7- &a{papi: ninjaxx_top_13_points} pts
/hd addline ninjaxx_top50 &e#14 &f{papi: ninjaxx_top_14_name} &7- &a{papi: ninjaxx_top_14_points} pts
/hd addline ninjaxx_top50 &e#15 &f{papi: ninjaxx_top_15_name} &7- &a{papi: ninjaxx_top_15_points} pts
/hd addline ninjaxx_top50 &e#16 &f{papi: ninjaxx_top_16_name} &7- &a{papi: ninjaxx_top_16_points} pts
/hd addline ninjaxx_top50 &e#17 &f{papi: ninjaxx_top_17_name} &7- &a{papi: ninjaxx_top_17_points} pts
/hd addline ninjaxx_top50 &e#18 &f{papi: ninjaxx_top_18_name} &7- &a{papi: ninjaxx_top_18_points} pts
/hd addline ninjaxx_top50 &e#19 &f{papi: ninjaxx_top_19_name} &7- &a{papi: ninjaxx_top_19_points} pts
/hd addline ninjaxx_top50 &e#20 &f{papi: ninjaxx_top_20_name} &7- &a{papi: ninjaxx_top_20_points} pts
/hd addline ninjaxx_top50 &e#21 &f{papi: ninjaxx_top_21_name} &7- &a{papi: ninjaxx_top_21_points} pts
/hd addline ninjaxx_top50 &e#22 &f{papi: ninjaxx_top_22_name} &7- &a{papi: ninjaxx_top_22_points} pts
/hd addline ninjaxx_top50 &e#23 &f{papi: ninjaxx_top_23_name} &7- &a{papi: ninjaxx_top_23_points} pts
/hd addline ninjaxx_top50 &e#24 &f{papi: ninjaxx_top_24_name} &7- &a{papi: ninjaxx_top_24_points} pts
/hd addline ninjaxx_top50 &e#25 &f{papi: ninjaxx_top_25_name} &7- &a{papi: ninjaxx_top_25_points} pts
/hd addline ninjaxx_top50 &e#26 &f{papi: ninjaxx_top_26_name} &7- &a{papi: ninjaxx_top_26_points} pts
/hd addline ninjaxx_top50 &e#27 &f{papi: ninjaxx_top_27_name} &7- &a{papi: ninjaxx_top_27_points} pts
/hd addline ninjaxx_top50 &e#28 &f{papi: ninjaxx_top_28_name} &7- &a{papi: ninjaxx_top_28_points} pts
/hd addline ninjaxx_top50 &e#29 &f{papi: ninjaxx_top_29_name} &7- &a{papi: ninjaxx_top_29_points} pts
/hd addline ninjaxx_top50 &e#30 &f{papi: ninjaxx_top_30_name} &7- &a{papi: ninjaxx_top_30_points} pts
/hd addline ninjaxx_top50 &e#31 &f{papi: ninjaxx_top_31_name} &7- &a{papi: ninjaxx_top_31_points} pts
/hd addline ninjaxx_top50 &e#32 &f{papi: ninjaxx_top_32_name} &7- &a{papi: ninjaxx_top_32_points} pts
/hd addline ninjaxx_top50 &e#33 &f{papi: ninjaxx_top_33_name} &7- &a{papi: ninjaxx_top_33_points} pts
/hd addline ninjaxx_top50 &e#34 &f{papi: ninjaxx_top_34_name} &7- &a{papi: ninjaxx_top_34_points} pts
/hd addline ninjaxx_top50 &e#35 &f{papi: ninjaxx_top_35_name} &7- &a{papi: ninjaxx_top_35_points} pts
/hd addline ninjaxx_top50 &e#36 &f{papi: ninjaxx_top_36_name} &7- &a{papi: ninjaxx_top_36_points} pts
/hd addline ninjaxx_top50 &e#37 &f{papi: ninjaxx_top_37_name} &7- &a{papi: ninjaxx_top_37_points} pts
/hd addline ninjaxx_top50 &e#38 &f{papi: ninjaxx_top_38_name} &7- &a{papi: ninjaxx_top_38_points} pts
/hd addline ninjaxx_top50 &e#39 &f{papi: ninjaxx_top_39_name} &7- &a{papi: ninjaxx_top_39_points} pts
/hd addline ninjaxx_top50 &e#40 &f{papi: ninjaxx_top_40_name} &7- &a{papi: ninjaxx_top_40_points} pts
/hd addline ninjaxx_top50 &e#41 &f{papi: ninjaxx_top_41_name} &7- &a{papi: ninjaxx_top_41_points} pts
/hd addline ninjaxx_top50 &e#42 &f{papi: ninjaxx_top_42_name} &7- &a{papi: ninjaxx_top_42_points} pts
/hd addline ninjaxx_top50 &e#43 &f{papi: ninjaxx_top_43_name} &7- &a{papi: ninjaxx_top_43_points} pts
/hd addline ninjaxx_top50 &e#44 &f{papi: ninjaxx_top_44_name} &7- &a{papi: ninjaxx_top_44_points} pts
/hd addline ninjaxx_top50 &e#45 &f{papi: ninjaxx_top_45_name} &7- &a{papi: ninjaxx_top_45_points} pts
/hd addline ninjaxx_top50 &e#46 &f{papi: ninjaxx_top_46_name} &7- &a{papi: ninjaxx_top_46_points} pts
/hd addline ninjaxx_top50 &e#47 &f{papi: ninjaxx_top_47_name} &7- &a{papi: ninjaxx_top_47_points} pts
/hd addline ninjaxx_top50 &e#48 &f{papi: ninjaxx_top_48_name} &7- &a{papi: ninjaxx_top_48_points} pts
/hd addline ninjaxx_top50 &e#49 &f{papi: ninjaxx_top_49_name} &7- &a{papi: ninjaxx_top_49_points} pts
/hd addline ninjaxx_top50 &e#50 &f{papi: ninjaxx_top_50_name} &7- &a{papi: ninjaxx_top_50_points} pts